version: "3.8"

services:
  ollama:
    build: .
    container_name: ollama-server
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_PORT=11434
    volumes:
      - ollama-models:/root/.ollama/models
      - ./models:/models:ro
      - ./data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama-models:
    driver: local
